/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const DlnaProfileType = {
    Audio: 'Audio',
    Video: 'Video',
    Photo: 'Photo'
} as const;

export type DlnaProfileType = typeof DlnaProfileType[keyof typeof DlnaProfileType];



