/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enum PlayCommand.
 * @export
 * @enum {string}
 */

export const PlayCommand = {
    PlayNow: 'PlayNow',
    PlayNext: 'PlayNext',
    PlayLast: 'PlayLast',
    PlayInstantMix: 'PlayInstantMix',
    PlayShuffle: 'PlayShuffle'
} as const;

export type PlayCommand = typeof PlayCommand[keyof typeof PlayCommand];



