/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An enum representing the sorting order.
 * @export
 * @enum {string}
 */

export const SortOrder = {
    Ascending: 'Ascending',
    Descending: 'Descending'
} as const;

export type SortOrder = typeof SortOrder[keyof typeof SortOrder];



