/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The base item kind.
 * @export
 * @enum {string}
 */
export enum BaseItemKind {
    AggregateFolder = 'AggregateFolder',
    Audio = 'Audio',
    AudioBook = 'AudioBook',
    BasePluginFolder = 'BasePluginFolder',
    Book = 'Book',
    BoxSet = 'BoxSet',
    Channel = 'Channel',
    ChannelFolderItem = 'ChannelFolderItem',
    CollectionFolder = 'CollectionFolder',
    Episode = 'Episode',
    Folder = 'Folder',
    Genre = 'Genre',
    ManualPlaylistsFolder = 'ManualPlaylistsFolder',
    Movie = 'Movie',
    MusicAlbum = 'MusicAlbum',
    MusicArtist = 'MusicArtist',
    MusicGenre = 'MusicGenre',
    MusicVideo = 'MusicVideo',
    Person = 'Person',
    Photo = 'Photo',
    PhotoAlbum = 'PhotoAlbum',
    Playlist = 'Playlist',
    Program = 'Program',
    Recording = 'Recording',
    Season = 'Season',
    Series = 'Series',
    Studio = 'Studio',
    Trailer = 'Trailer',
    TvChannel = 'TvChannel',
    TvProgram = 'TvProgram',
    UserRootFolder = 'UserRootFolder',
    UserView = 'UserView',
    Video = 'Video',
    Year = 'Year'
}



