/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enum describing the location of the FFmpeg tool.
 * @export
 * @enum {string}
 */

export const FFmpegLocation = {
    NotFound: 'NotFound',
    SetByArgument: 'SetByArgument',
    Custom: 'Custom',
    System: 'System'
} as const;

export type FFmpegLocation = typeof FFmpegLocation[keyof typeof FFmpegLocation];



