version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: '/stable'
    schedule:
      interval: weekly
      time: '00:00'
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: '/unstable'
    schedule:
      interval: weekly
      time: '00:00'
    open-pull-requests-limit: 10
