/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ClientLogDocumentResponseDto } from '../models';
// @ts-ignore
import { ClientLogEventDto } from '../models';
// @ts-ignore
import { ProblemDetails } from '../models';
/**
 * ClientLogApi - axios parameter creator
 * @export
 */
export const ClientLogApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Post event from client.
         * @param {ClientLogEventDto} [clientLogEventDto] The client log dto.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logEvent: async (clientLogEventDto?: ClientLogEventDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ClientLog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CustomAuthentication required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(clientLogEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Bulk post events from client.
         * @param {Array<ClientLogEventDto>} [clientLogEventDto] The list of client log dtos.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logEvents: async (clientLogEventDto?: Array<ClientLogEventDto>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ClientLog/Bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CustomAuthentication required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(clientLogEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload a document.
         * @param {any} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logFile: async (body?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ClientLog/Document`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CustomAuthentication required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ClientLogApi - functional programming interface
 * @export
 */
export const ClientLogApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ClientLogApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Post event from client.
         * @param {ClientLogEventDto} [clientLogEventDto] The client log dto.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logEvent(clientLogEventDto?: ClientLogEventDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logEvent(clientLogEventDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Bulk post events from client.
         * @param {Array<ClientLogEventDto>} [clientLogEventDto] The list of client log dtos.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logEvents(clientLogEventDto?: Array<ClientLogEventDto>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logEvents(clientLogEventDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Upload a document.
         * @param {any} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logFile(body?: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClientLogDocumentResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logFile(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ClientLogApi - factory interface
 * @export
 */
export const ClientLogApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ClientLogApiFp(configuration)
    return {
        /**
         * 
         * @summary Post event from client.
         * @param {ClientLogEventDto} [clientLogEventDto] The client log dto.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logEvent(clientLogEventDto?: ClientLogEventDto, options?: any): AxiosPromise<void> {
            return localVarFp.logEvent(clientLogEventDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Bulk post events from client.
         * @param {Array<ClientLogEventDto>} [clientLogEventDto] The list of client log dtos.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logEvents(clientLogEventDto?: Array<ClientLogEventDto>, options?: any): AxiosPromise<void> {
            return localVarFp.logEvents(clientLogEventDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload a document.
         * @param {any} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logFile(body?: any, options?: any): AxiosPromise<ClientLogDocumentResponseDto> {
            return localVarFp.logFile(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for logEvent operation in ClientLogApi.
 * @export
 * @interface ClientLogApiLogEventRequest
 */
export interface ClientLogApiLogEventRequest {
    /**
     * The client log dto.
     * @type {ClientLogEventDto}
     * @memberof ClientLogApiLogEvent
     */
    readonly clientLogEventDto?: ClientLogEventDto
}

/**
 * Request parameters for logEvents operation in ClientLogApi.
 * @export
 * @interface ClientLogApiLogEventsRequest
 */
export interface ClientLogApiLogEventsRequest {
    /**
     * The list of client log dtos.
     * @type {Array<ClientLogEventDto>}
     * @memberof ClientLogApiLogEvents
     */
    readonly clientLogEventDto?: Array<ClientLogEventDto>
}

/**
 * Request parameters for logFile operation in ClientLogApi.
 * @export
 * @interface ClientLogApiLogFileRequest
 */
export interface ClientLogApiLogFileRequest {
    /**
     * 
     * @type {any}
     * @memberof ClientLogApiLogFile
     */
    readonly body?: any
}

/**
 * ClientLogApi - object-oriented interface
 * @export
 * @class ClientLogApi
 * @extends {BaseAPI}
 */
export class ClientLogApi extends BaseAPI {
    /**
     * 
     * @summary Post event from client.
     * @param {ClientLogApiLogEventRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClientLogApi
     */
    public logEvent(requestParameters: ClientLogApiLogEventRequest = {}, options?: AxiosRequestConfig) {
        return ClientLogApiFp(this.configuration).logEvent(requestParameters.clientLogEventDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Bulk post events from client.
     * @param {ClientLogApiLogEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClientLogApi
     */
    public logEvents(requestParameters: ClientLogApiLogEventsRequest = {}, options?: AxiosRequestConfig) {
        return ClientLogApiFp(this.configuration).logEvents(requestParameters.clientLogEventDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload a document.
     * @param {ClientLogApiLogFileRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClientLogApi
     */
    public logFile(requestParameters: ClientLogApiLogFileRequest = {}, options?: AxiosRequestConfig) {
        return ClientLogApiFp(this.configuration).logFile(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}
