name: Generate stable and unstable API

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        version:
          - stable
          - unstable

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Download OpenAPI file
        run: curl -s https://api.jellyfin.org/openapi/jellyfin-openapi-${{ matrix.version }}.json > openapi.json

      - name: Modify the schema
        run: node scripts/modifySchema.mjs openapi.json

      - name: Generate
        uses: docker://openapitools/openapi-generator-cli:latest-release
        env:
          TS_POST_PROCESS_FILE: true
        with:
          args: >-
            generate -i /github/workspace/openapi.json
            -g typescript-axios --additional-properties=npmName=@jellyfin/client-axios
            --additional-properties=npmRepository=https://www.npmjs.com/package/@jellyfin/client-axios
            --additional-properties=supportsES6=true
            --additional-properties=useSingleRequestParameter=true
            --additional-properties=withSeparateModelsAndApi=true
            --additional-properties=modelPackage=models
            --additional-properties=apiPackage=api
            --enable-post-process-file
            -o /github/workspace/${{ matrix.version }}

      - name: Check if .ts files were modified
        id: diff
        run: echo "::set-output name=count::$(git status -su | grep ts | wc -l)"

      - name: Set docker files ownership to runner
        if: ${{ steps.diff.outputs.count > 0 }}
        run: sudo chown -R runner:docker .

      - name: (stable) Set version in package.json
        if: ${{ steps.diff.outputs.count > 0 && matrix.version == 'stable' }}
        run: |
          VERSION=$(cat openapi.json | jq '.info.version')
          echo "$(cat stable/package.json | jq ".version = $VERSION")" > stable/package.json
          echo "$(cat stable/package-lock.json | jq ".version = $VERSION")" > stable/package-lock.json

      - name: (unstable) Set version in package.json
        if: ${{ steps.diff.outputs.count > 0 && matrix.version == 'unstable' }}
        run: |
          SERVER_SHA="$(git ls-remote git://github.com/jellyfin/jellyfin.git | grep refs/heads/master | cut -f 1  | cut -c1-7)"
          SERVER_VERSION="$(cat openapi.json | jq '.info.version')"
          SERVER_VERSION=${SERVER_VERSION:1:-1}
          VERSION=$(echo "$SERVER_VERSION-unstable+$SERVER_SHA")
          echo "$(cat unstable/package.json | jq ".version = \"${VERSION}\"")" > unstable/package.json
          echo "$(cat unstable/package-lock.json | jq ".version = \"${VERSION}\"")" > unstable/package-lock.json

      - name: Setup node environment
        if: ${{ steps.diff.outputs.count > 0 }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: ${{ matrix.version }}/package-lock.json

      - name: Install dependencies
        if: ${{ steps.diff.outputs.count > 0 }}
        run: npm ci --no-audit
        working-directory: ./${{ matrix.version }}

      - name: Build
        if: ${{ steps.diff.outputs.count > 0 }}
        run: npm run build
        working-directory: ./${{ matrix.version }}

      # "echo" in commit returns true so the build succeeds, even if no changed files
      - name: Commit new changes to the repo
        if: ${{ steps.diff.outputs.count > 0 && github.event_name != 'pull_request' }}
        run: |
          git config --global user.email "packaging@jellyfin.org"
          git config --global user.name "Jellyfin Packaging Team"
          git pull
          git add .
          git commit -m "Update ${{ matrix.version }} OpenAPI client" || echo
          git push
